[workspace]
[package]
name = "create-account-crate"
version = "0.1.0"
edition = "2021"
publish = false

# Specify lib target explicitly for clarity if needed, though Cargo usually infers it
[lib]
crate-type = ["cdylib", "lib"] # Keep existing types

[dependencies]
solana-program = { version = "2.2.0", default-features = false }
